dist: trusty

script:
  - docker build -t navicore/naviron-other .
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

sudo: required

services:
  - docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push navicore/naviron-other;
    docker tag "navicore/naviron-other" "navicore/naviron-other:0.1.$TRAVIS_BUILD_NUMBER";
    docker push "navicore/naviron-other:0.1.$TRAVIS_BUILD_NUMBER";
    fi

